name: Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true

      - uses: rubygems/configure-rubygems-credentials@v1.0.0

      - name: Build gem
        run: gem build spotify-client.gemspec

      - name: Publish gem
        run: gem push spotify-client-*.gem
